### This configuration file is for typos-cli, a command-line tool designed to detect and correct typos in text files. (Install typos-cli here: https://github.com/crate-ci/typos)
### Add words, identiifers, and regex patterns to this file to be ignored.
### Reference: https://github.com/crate-ci/typos/blob/master/docs/reference.md

# Ignore words
[default.extend-words]
OTP = "OTP"
OTPs = "OTPs"

# Ignore identifiers
[default.extend-identifiers]
OTP = "OTP"
OTPs = "OTPs"

#Ignore filetype example
[type.po]
extend-glob = ["*.po"]
check-file = false